POST https://library-management-system-mfmtcnu6ba-em.a.run.app/lms/api/v1/library
Content-Type: application/json

{
  "name": "National Library",
  "address": {
    "zipCode": "100009"
  }
}

###

GET https://library-management-system-mfmtcnu6ba-em.a.run.app/lms/api/v1/libraries
Content-Type: application/json
